### ISSUE TITLE
where is install_mfa.sh?

### ISSUE THREAD

**Issue by FlyToYourMooN** [Zain-Jiang/Speech-Editing-Toolkit#1]
Sorry i can't find it.

**Comment by Zain-Jiang** [comment]
I'm sorry that is a mistake in our readme. You can install the Montreal Forced Aligner 2.x following the official instruction in https://montreal-forced-aligner.readthedocs.io/en/latest/. Thank you for pointing out this.

**Comment by Zain-Jiang** [comment]
Thank you for pointing out this bug. If you have no further questions, I will close this issue a few days later.
