### ISSUE TITLE
Any checkpoints

### ISSUE THREAD

**Issue by yyua8222** [Zain-Jiang/Speech-Editing-Toolkit#3]
Hi, thanks for this amazing work, I am just wondering if we can provide any checkpoints to run for speech editing.

**Comment by Zain-Jiang** [comment]
Yes, we are preparing the pretrained ckpts at VCTK and LibriTTS. The ckpts will be provided in two days.

**Comment by mvoodarla** [comment]
Also curious about this. Thanks for your great work!

**Comment by Zain-Jiang** [comment]
We have published our pre-trained ckpts at LibriTTS. Thanks for your attentions and supports!
